# Config file for continuous integration.

[rust]
codegen-units = 0           # Use many compilation units.
debug-assertions = true     # Turn on assertions in rustc.

[build]
docs = false
extended = true
tools = ["cargo", "rustdoc"]

[llvm]
assertions = true           # Turn on assertions in LLVM.

# `x.py install` is currently broken.
# https://github.com/rust-lang/rust/issues/80683
#[install]
#prefix = "build/ykrustc-stage2-latest"
#sysconfdir = "etc"
